sudo: false
dist: trusty

language: cpp

compiler: clang

git:
  depth: 2
  quiet: true

cache:
  timeout: 1000
  directories:
  - $HOME/llvm
  - $HOME/build

env:
  global:
    - TIMEOUT=2700

before_script:
    - if [[ -d $HOME/llvm/tools/clang ]]; then
        cd $HOME/llvm && git pull;
        cd $HOME/llvm/tools/clang && git pull;
      else
        git clone --depth=2 https://github.com/llvm-mirror/llvm.git $HOME/llvm -b release_70; 
        git clone --depth=2 https://github.com/llvm-mirror/clang.git $HOME/llvm/tools/clang -b release_70;        
        mkdir -p $HOME/llvm/tools/clang/tools/extra;
        mkdir -p $HOME/build;
      fi
    - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/llvm/tools/clang/tools/extra/
    - export TRAVIS_BUILD_DIR=$HOME/llvm/tools/clang/tools/extra/
    - cd $HOME/build
    - if [[ -f touch_mtimes.txt ]]; then 
       while read mtime fn; do touch -c -m -d "@$mtime" $fn; done < touch_mtimes.txt;
       cut -f 1 -d ' ' touch_mtimes.txt | sort | read OLDEST_MTIME;
       export OLDEST_MTIME=$((OLDEST_MTIME-1));
       find "${TRAVIS_BUILD_DIR}" -type f -exec touch -c -m -d "@$OLDEST_MTIME" {} \;
       cd "${TRAVIS_BUILD_DIR}";
       PREVIOUS_GIT_COMMIT="HEAD~1";
       if [[ -f previous_git_commit.txt ]]; then read PREVIOUS_GIT_COMMIT < previous_git_commit.txt; fi;
       export PREVIOUS_GIT_COMMIT;
       changed_files=`git diff --name-only $PREVIOUS_GIT_COMMIT HEAD`;
       echo "Previously cached Travis build based on git commit ${PREVIOUS_GIT_COMMIT}.";
       echo "... changed files since then:";
       echo $changed_files;
       touch `echo $changed_files`;
       cd $HOME/build;
      else
       cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DLLVM_TARGETS_TO_BUILD="X86" $HOME/llvm;
      fi
script: 
    - timeout $TIMEOUT make -j2  check-clang-tools RESULT=$?; if [ "$RESULT" -eq 127 ]; then RESULT = 0; if [ "$RESULT" -eq 0 ]; then mkdir Compleated; fi; fi;
before_cache:
    - if [[ -d Compleated ]]; then 
       find . -type f -printf "%.10T@ %p\n" > touch_mtimes.txt;
       cd "${TRAVIS_BUILD_DIR}" && git rev-parse HEAD > $HOME/build/previous_git_commit.txt;     
      fi
